import { Pool } from 'pg';
import { runMigrations } from './schema';
import { createQueryable } from './client';

const url = process.env.TEST_DATABASE_URL;
const run = url ? describe : describe.skip;

run('migration 012 backfill', () => {
  it('moves pre-existing world_records.tags into world_tags and drops the column', async () => {
    const pool = new Pool({ connectionString: url });
    const schema = `sos_backfill_${Date.now()}`;
    try {
      await pool.query(`CREATE SCHEMA "${schema}"`);
      await pool.query(`SET search_path TO "${schema}", public`);
      const q = createQueryable(pool);

      await q.query(`
        CREATE TABLE world_records (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          world_id text NOT NULL,
          guild_id text NOT NULL,
          message_id text NOT NULL,
          name text,
          author_name text,
          capacity integer,
          platforms text[] NOT NULL DEFAULT '{}',
          tags text[] NOT NULL DEFAULT '{}',
          image_url text,
          source_content text,
          vrchat_data text,
          package_sizes double precision[] NOT NULL DEFAULT '{}',
          quality text CHECK (quality IN ('good', 'bad')),
          internal_add_date bigint,
          created_at bigint NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW()))::bigint,
          updated_at bigint NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW()))::bigint,
          UNIQUE (world_id, guild_id)
        )
      `);
      await q.query(
        `INSERT INTO world_records (world_id, guild_id, message_id, name, tags)
         VALUES ('wrld_old1', 'guild-1', '1', 'Old World', ARRAY['horror', 'game']),
                ('wrld_old2', 'guild-1', '2', 'Old World 2', ARRAY['game'])`
      );

      await runMigrations(q);

      const junction = await q.query<{ world_id: string; tag: string }>(
        `SELECT world_id, tag FROM world_tags ORDER BY world_id, tag`
      );
      expect(junction.rows).toEqual([
        { world_id: 'wrld_old1', tag: 'game' },
        { world_id: 'wrld_old1', tag: 'horror' },
        { world_id: 'wrld_old2', tag: 'game' }
      ]);

      const columns = await q.query<{ column_name: string }>(
        `SELECT column_name FROM information_schema.columns
         WHERE table_name = 'world_records'`
      );
      expect(columns.rows.some((r) => r.column_name === 'tags')).toBe(false);
    } finally {
      await pool.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);
      await pool.end();
    }
  });
});
