import type { Queryable } from './client';
import logger from '../logger';

interface Migration {
  name: string;
  run: (db: Queryable) => Promise<void>;
}

const EPOCH_NOW = `(EXTRACT(EPOCH FROM NOW()))::bigint`;

const MIGRATIONS: Migration[] = [
  {
    name: '001_create_world_records',
    run: async (db) => {
      await db.query(`
        CREATE TABLE IF NOT EXISTS world_records (
          id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          world_id          text    NOT NULL,
          guild_id          text    NOT NULL,
          message_id        text    NOT NULL,
          name              text,
          author_name       text,
          capacity          integer,
          platforms         text[]              NOT NULL DEFAULT '{}',
          tags              text[]              NOT NULL DEFAULT '{}',
          image_url         text,
          source_content    text,
          vrchat_data       text,
          package_sizes     double precision[]  NOT NULL DEFAULT '{}',
          quality           text CHECK (quality IN ('good', 'bad')),
          internal_add_date bigint,
          created_at        bigint  NOT NULL DEFAULT ${EPOCH_NOW},
          updated_at        bigint  NOT NULL DEFAULT ${EPOCH_NOW},
          UNIQUE (world_id, guild_id)
        );
      `);
      await db.query(
        `CREATE INDEX IF NOT EXISTS idx_worlds_world_id ON world_records(world_id)`
      );
      await db.query(
        `CREATE INDEX IF NOT EXISTS idx_worlds_guild_id ON world_records(guild_id)`
      );
      await db.query(
        `CREATE INDEX IF NOT EXISTS idx_worlds_created_at ON world_records(created_at)`
      );
      await db.query(
        `CREATE INDEX IF NOT EXISTS idx_worlds_capacity ON world_records(capacity)`
      );
      await db.query(
        `CREATE INDEX IF NOT EXISTS idx_worlds_tags_gin ON world_records USING GIN (tags)`
      );
      await db.query(
        `CREATE INDEX IF NOT EXISTS idx_worlds_platforms_gin ON world_records USING GIN (platforms)`
      );
    }
  },
  {
    name: '002_create_deleted_world_records',
    run: async (db) => {
      await db.query(`
        CREATE TABLE IF NOT EXISTS deleted_world_records (
          id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          world_id          text    NOT NULL,
          guild_id          text    NOT NULL,
          message_id        text    NOT NULL,
          name              text,
          author_name       text,
          capacity          integer,
          platforms         text[]              NOT NULL DEFAULT '{}',
          tags              text[]              NOT NULL DEFAULT '{}',
          image_url         text,
          source_content    text,
          vrchat_data       text,
          package_sizes     double precision[]  NOT NULL DEFAULT '{}',
          internal_add_date bigint,
          created_at        bigint  NOT NULL DEFAULT ${EPOCH_NOW},
          updated_at        bigint  NOT NULL DEFAULT ${EPOCH_NOW},
          deleted_at        bigint  NOT NULL DEFAULT ${EPOCH_NOW}
        );
      `);
      await db.query(
        `CREATE INDEX IF NOT EXISTS idx_deleted_worlds_world_id ON deleted_world_records(world_id)`
      );
      await db.query(
        `CREATE INDEX IF NOT EXISTS idx_deleted_worlds_guild_id ON deleted_world_records(guild_id)`
      );
    }
  },
  {
    name: '003_add_quality_column',
    run: async () => {
      // quality is part of the base world_records table above.
    }
  },
  {
    name: '004_add_capacity_index',
    run: async () => {
      // capacity index is part of the base world_records table above.
    }
  },
  {
    name: '005_add_internal_add_date_column',
    run: async () => {
      // internal_add_date is part of the base world_records table above.
    }
  },
  {
    name: '006_create_roles_and_api_tokens',
    run: async (db) => {
      await db.query(`
        CREATE TABLE IF NOT EXISTS roles (
          id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name        text    NOT NULL UNIQUE,
          permissions text[]  NOT NULL DEFAULT '{}',
          created_at  bigint  NOT NULL DEFAULT ${EPOCH_NOW}
        );
      `);
      await db.query(`
        CREATE TABLE IF NOT EXISTS api_tokens (
          id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          token_hash   text    NOT NULL UNIQUE,
          name         text    NOT NULL,
          role_id      bigint  NOT NULL REFERENCES roles(id),
          created_at   bigint  NOT NULL DEFAULT ${EPOCH_NOW},
          last_used_at bigint,
          revoked_at   bigint
        );
      `);
      await db.query(
        `CREATE INDEX IF NOT EXISTS idx_api_tokens_role_id ON api_tokens(role_id)`
      );

      const roleCount = await db.query<{ count: number }>(
        `SELECT COUNT(*)::int AS count FROM roles`
      );
      if ((roleCount.rows[0]?.count ?? 0) > 0) {
        return;
      }

      await db.query(
        `INSERT INTO roles (name, permissions) VALUES
          ($1, $2::text[]),
          ($3, $4::text[]),
          ($5, $6::text[])`,
        [
          'viewer',
          ['worlds:read', 'tags:read', 'meta:read'],
          'curator',
          ['worlds:read', 'tags:read', 'meta:read', 'worlds:write'],
          'admin',
          ['worlds:read', 'tags:read', 'meta:read', 'worlds:write']
        ]
      );
    }
  },
  {
    name: '007_add_package_sizes_column',
    run: async () => {
      // package_sizes is part of the base world_records table above.
    }
  },
  {
    name: '008_create_high_priority_worlds',
    run: async (db) => {
      await db.query(`
        CREATE TABLE IF NOT EXISTS high_priority_worlds (
          world_id          text    NOT NULL,
          guild_id          text    NOT NULL,
          added_at          bigint  NOT NULL DEFAULT ${EPOCH_NOW},
          added_by_token_id bigint  REFERENCES api_tokens(id) ON DELETE SET NULL,
          PRIMARY KEY (world_id, guild_id),
          FOREIGN KEY (world_id, guild_id)
            REFERENCES world_records(world_id, guild_id) ON DELETE CASCADE
        );
      `);
    }
  },
  {
    name: '009_grant_tags_write_to_curator_and_admin',
    run: async (db) => {
      const selectStmt = `SELECT permissions FROM roles WHERE name = $1`;
      const updateStmt = `UPDATE roles SET permissions = $1 WHERE name = $2`;
      for (const roleName of ['curator', 'admin']) {
        const row = await db.query<{ permissions: string[] }>(selectStmt, [
          roleName
        ]);
        const permissions = row.rows[0]?.permissions;
        if (!permissions || !permissions.includes('tags:write')) {
          if (!permissions) {
            continue;
          }
          permissions.push('tags:write');
          await db.query(updateStmt, [permissions, roleName]);
        }
      }
    }
  }
];

/**
 * Run all pending migrations on the given database within transactions.
 * Tracks applied migrations in _migrations so each runs only once.
 */
export async function runMigrations(db: Queryable): Promise<void> {
  await db.query(`CREATE TABLE IF NOT EXISTS _migrations (
    name text PRIMARY KEY,
    applied_at bigint NOT NULL DEFAULT ${EPOCH_NOW}
  )`);

  const appliedRows = await db.query<{ name: string }>(
    `SELECT name FROM _migrations`
  );
  const appliedNames = new Set(appliedRows.rows.map((r) => r.name));

  for (let i = 0; i < MIGRATIONS.length; i++) {
    const migration = MIGRATIONS[i];
    if (appliedNames.has(migration.name)) {
      continue;
    }

    try {
      await db.withTransaction(async (tx) => {
        await migration.run(tx);
        await tx.query(`INSERT INTO _migrations (name) VALUES ($1)`, [
          migration.name
        ]);
      });
      logger.info(
        `Migration ${i + 1}/${MIGRATIONS.length} applied: ${migration.name}`
      );
    } catch (error) {
      logger.error(`Migration ${migration.name} failed:`, error);
      throw error;
    }
  }
}
