import { Pool } from 'pg';
import request from 'supertest';
import type { Express } from 'express';

/**
 * Full smoke of the tags catalog + world_tags junction against real
 * Postgres. Creates a fresh database with pre-migration world_records (the
 * legacy tags text[] column, populated like production), runs all
 * migrations, then exercises the repository layer and the live HTTP API
 * (auth included) against the migrated schema.
 *
 * Skips unless SMOKE_DATABASE_URL is set to a dedicated throwaway database,
 * e.g. `createdb sos_world_tagger_smoke`.
 */
const url = process.env.SMOKE_DATABASE_URL;
const run = url ? describe : describe.skip;

run('full smoke: tags catalog + world_tags junction', () => {
  let pool: Pool;
  let app: Express;
  let curatorToken: string;
  let viewerToken: string;

  beforeAll(async () => {
    process.env.DATABASE_URL = url!;

    const { createQueryable } = await import('./client.js');
    const { runMigrations } = await import('./schema.js');
    const { createApiServer } = await import('../apiServer/index.js');
    const { RoleRepository } = await import('./roleRepository.js');
    const { TokenRepository } = await import('./tokenRepository.js');
    const { TagRepository } = await import('./tagRepository.js');

    pool = new Pool({ connectionString: url! });
    const queryable = createQueryable(pool);

    // Dedicated throwaway database: reset to a clean slate each run so a
    // previous run's migrated state cannot leak into this one.
    await pool.query(`DROP SCHEMA public CASCADE`);
    await pool.query(`CREATE SCHEMA public`);

    // Simulate the pre-migration schema: world_records with the legacy
    // tags text[] column, populated with realistic data. One world carries
    // a tag that is not in the canonical catalog to exercise the 012
    // safety insert and the display fallback.
    await queryable.query(`
      CREATE TABLE world_records (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        world_id text NOT NULL,
        guild_id text NOT NULL,
        message_id text NOT NULL,
        name text,
        author_name text,
        capacity integer,
        platforms text[] NOT NULL DEFAULT '{}',
        tags text[] NOT NULL DEFAULT '{}',
        image_url text,
        source_content text,
        vrchat_data text,
        package_sizes double precision[] NOT NULL DEFAULT '{}',
        quality text CHECK (quality IN ('good', 'bad')),
        internal_add_date bigint,
        created_at bigint NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW()))::bigint,
        updated_at bigint NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW()))::bigint,
        UNIQUE (world_id, guild_id)
      )
    `);
    await queryable.query(`
      INSERT INTO world_records (world_id, guild_id, message_id, name, capacity, tags, source_content, quality) VALUES
        ('wrld_horror', 'guild-1', '100', 'Spooky Mansion', 16, ARRAY['horror', 'game'], 'tap jump run', 'good'),
        ('wrld_chill',  'guild-1', '101', 'Cozy Cabin', 8, ARRAY['chill'], 'relax', NULL),
        ('wrld_kino',   'guild-1', '102', 'Cinema Club', 24, ARRAY['kino', 'chill', 'space'], 'movies', NULL),
        ('wrld_legacy', 'guild-2', '103', 'Old World', 4, ARRAY['legacy-unknown'], NULL, NULL),
        ('wrld_empty',  'guild-1', '104', 'Empty World', 4, ARRAY[]::text[], NULL, NULL)
    `);

    await runMigrations(queryable);

    const { setTaxonomy } = await import('../tags/extractor.js');
    const canonicalTags = await new TagRepository(queryable).getAll();
    setTaxonomy(canonicalTags.map((t) => t.tag));

    const roles = new RoleRepository(queryable);
    const tokens = new TokenRepository(queryable);
    const curator = await tokens.create(
      'smoke-curator',
      (await roles.findByName('curator'))!
    );
    const viewer = await tokens.create(
      'smoke-viewer',
      (await roles.findByName('viewer'))!
    );
    curatorToken = curator.rawToken;
    viewerToken = viewer.rawToken;

    app = createApiServer();
  });

  afterAll(async () => {
    const { closePool } = await import('./pool.js');
    await closePool();
    await pool.end();
  });

  describe('migration 012 on real data', () => {
    it('backfills world_tags, seeds unknown tags with fallback metadata, drops the column', async () => {
      const { createQueryable } = await import('./client.js');
      const queryable = createQueryable(pool);

      const junction = await queryable.query<{ world_id: string; tag: string }>(
        `SELECT world_id, tag FROM world_tags ORDER BY world_id, tag`
      );
      expect(junction.rows).toEqual([
        { world_id: 'wrld_chill', tag: 'chill' },
        { world_id: 'wrld_horror', tag: 'game' },
        { world_id: 'wrld_horror', tag: 'horror' },
        { world_id: 'wrld_kino', tag: 'chill' },
        { world_id: 'wrld_kino', tag: 'kino' },
        { world_id: 'wrld_kino', tag: 'space' },
        { world_id: 'wrld_legacy', tag: 'legacy-unknown' }
      ]);

      const catalog = await queryable.query<{
        tag: string;
        emoji: string;
        hex_color: string;
      }>(`SELECT tag, emoji, hex_color FROM tags WHERE tag = 'legacy-unknown'`);
      expect(catalog.rows).toEqual([
        { tag: 'legacy-unknown', emoji: '❓', hex_color: '#94a3b8' }
      ]);

      const columns = await queryable.query<{ column_name: string }>(
        `SELECT column_name FROM information_schema.columns
         WHERE table_name = 'world_records'`
      );
      expect(columns.rows.some((r) => r.column_name === 'tags')).toBe(false);
    });
  });

  describe('repository layer on the migrated schema', () => {
    it('reads tags back in their original order', async () => {
      const { createQueryable } = await import('./client.js');
      const { WorldRepository } = await import('./worldRepository.js');
      const repo = new WorldRepository(createQueryable(pool));

      const record = await repo.getByWorldId('wrld_horror');
      expect(record?.tags).toEqual(['horror', 'game']);
      const kino = await repo.getByWorldId('wrld_kino');
      expect(kino?.tags).toEqual(['kino', 'chill', 'space']);
      const empty = await repo.getByWorldId('wrld_empty');
      expect(empty?.tags).toEqual([]);
    });

    it('upserts new worlds into the junction and replaces tags on update', async () => {
      const { createQueryable } = await import('./client.js');
      const { WorldRepository } = await import('./worldRepository.js');
      const repo = new WorldRepository(createQueryable(pool));

      await repo.upsert({
        worldId: 'wrld_new',
        guildId: 'guild-1',
        messageId: '200',
        name: 'New World',
        authorName: 'Author',
        capacity: 8,
        platforms: ['standalonewindows'],
        tags: ['chill', 'horror'],
        imageUrl: null,
        sourceContent: 'new world chill',
        vrchatData: null,
        packageSizes: []
      });
      expect(
        (await repo.getByWorldId('wrld_new'))?.tags
      ).toEqual(['chill', 'horror']);

      await repo.upsert({
        worldId: 'wrld_new',
        guildId: 'guild-1',
        messageId: '200',
        name: 'New World',
        authorName: 'Author',
        capacity: 8,
        platforms: ['standalonewindows'],
        tags: ['game'],
        imageUrl: null,
        sourceContent: 'new world chill',
        vrchatData: null,
        packageSizes: []
      });
      expect(
        (await repo.getByWorldId('wrld_new'))?.tags
      ).toEqual(['game']);
    });

    it('records the curator token on tag edits and preserves order', async () => {
      const { createQueryable } = await import('./client.js');
      const { WorldRepository } = await import('./worldRepository.js');
      const { TokenRepository } = await import('./tokenRepository.js');
      const repo = new WorldRepository(createQueryable(pool));

      const tokens = new TokenRepository(createQueryable(pool));
      const curatorRecord = (await tokens.findByName('smoke-curator'))!;

      const updated = await repo.updateTagsOnly('wrld_kino', ['space', 'chill'], curatorRecord.id);
      expect(updated).toBe(true);
      expect(
        (await repo.getByWorldId('wrld_kino'))?.tags
      ).toEqual(['space', 'chill']);

      const q = createQueryable(pool);
      const rows = await q.query<{ tag: string; added_by_token_id: number }>(
        `SELECT tag, added_by_token_id FROM world_tags WHERE world_id = 'wrld_kino' ORDER BY added_at, id`
      );
      expect(
        rows.rows.map((r) => ({
          tag: r.tag,
          added_by_token_id: Number(r.added_by_token_id)
        }))
      ).toEqual([
        { tag: 'space', added_by_token_id: curatorRecord.id },
        { tag: 'chill', added_by_token_id: curatorRecord.id }
      ]);
    });

    it('rejects attaching a tag that is not in the catalog (FK enforcement)', async () => {
      const { createQueryable } = await import('./client.js');
      const { WorldRepository } = await import('./worldRepository.js');
      const repo = new WorldRepository(createQueryable(pool));

      await expect(
        repo.upsert({
          worldId: 'wrld_fk',
          guildId: 'guild-1',
          messageId: '300',
          name: 'FK World',
          authorName: 'Author',
          capacity: 8,
          platforms: [],
          tags: ['not-a-real-tag'],
          imageUrl: null,
          sourceContent: null,
          vrchatData: null,
          packageSizes: []
        })
      ).rejects.toThrow();
    });

    it('deletes a world, cascades the junction, and archives the tag snapshot', async () => {
      const { createQueryable } = await import('./client.js');
      const { WorldRepository } = await import('./worldRepository.js');
      const repo = new WorldRepository(createQueryable(pool));

      const deleted = await repo.deleteByWorldId('wrld_empty');
      expect(deleted).toBe(true);

      const q = createQueryable(pool);
      const remaining = await q.query<{ world_id: string }>(
        `SELECT world_id FROM world_tags WHERE world_id = 'wrld_empty'`
      );
      expect(remaining.rows).toEqual([]);
      const archived = await q.query<{ tags: string[] }>(
        `SELECT tags FROM deleted_world_records WHERE world_id = 'wrld_empty'`
      );
      expect(archived.rows[0]?.tags).toEqual([]);
    });
  });

  describe('HTTP API against the migrated schema', () => {
    it('GET /api/tags returns every catalog tag with metadata, counts, and fallbacks', async () => {
      const response = await request(app)
        .get('/api/tags')
        .set('authorization', `Bearer ${viewerToken}`);
      expect(response.status).toBe(200);

      const byTag = new Map<
        string,
        { tag: string; count: number; emoji: string; hexColor: string }
      >();
      for (const t of response.body.tags) byTag.set(t.tag, t);

      // Counts from the junction. State reflects the repository tests above:
      // wrld_kino lost 'kino' to an updateTagsOnly call, wrld_empty was deleted.
      expect(byTag.get('horror')?.count).toBe(1);
      expect(byTag.get('game')?.count).toBe(2);
      expect(byTag.get('chill')?.count).toBe(2);
      expect(byTag.get('kino')?.count).toBe(0);

      // Every canonical tag present, unused at 0.
      const { TAG_SEED } = await import('./tagSeed.js');
      expect(response.body.tags).toHaveLength(TAG_SEED.length + 1);
      expect(byTag.get('aquatic')?.count).toBe(0);
      expect(byTag.get('aquatic')?.emoji).toBe('🐟');

      // Unknown in-data tag gets the fallback metadata.
      expect(byTag.get('legacy-unknown')).toEqual({
        tag: 'legacy-unknown',
        count: 1,
        emoji: '❓',
        hexColor: '#94a3b8'
      });

      // Sorted count-descending, ties alphabetical.
      const counts = response.body.tags.map((t: { count: number }) => t.count);
      expect(counts).toEqual([...counts].sort((a, b) => b - a));
      const zeroTags = response.body.tags
        .filter((t: { count: number }) => t.count === 0)
        .map((t: { tag: string }) => t.tag);
      expect(zeroTags).toEqual([...zeroTags].sort());
    });

    it('GET /api/worlds filters by tag and includes tags on the payload', async () => {
      const single = await request(app)
        .get('/api/worlds')
        .query({ tag: 'horror' })
        .set('authorization', `Bearer ${viewerToken}`);
      expect(single.status).toBe(200);
      expect(single.body.total).toBe(1);
      expect(single.body.worlds[0].worldId).toBe('wrld_horror');
      expect(single.body.worlds[0].tags).toEqual(['horror', 'game']);

      const multi = await request(app)
        .get('/api/worlds')
        .query({ tag: ['horror', 'game'] })
        .set('authorization', `Bearer ${viewerToken}`);
      expect(multi.body.total).toBe(1);

      const noMatch = await request(app)
        .get('/api/worlds')
        .query({ tag: ['horror', 'chill'] })
        .set('authorization', `Bearer ${viewerToken}`);
      expect(noMatch.body.total).toBe(0);
    });

    it('GET /api/worlds/:worldId includes tags from the junction', async () => {
      const response = await request(app)
        .get('/api/worlds/wrld_horror')
        .set('authorization', `Bearer ${viewerToken}`);
      expect(response.status).toBe(200);
      expect(response.body.tags).toEqual(['horror', 'game']);
    });

    it('PUT /api/worlds/:worldId/tags/edit updates the junction and records the curator', async () => {
      const response = await request(app)
        .put('/api/worlds/wrld_horror/tags/edit')
        .set('authorization', `Bearer ${curatorToken}`)
        .send({ guildId: 'guild-1', tags: ['horror', 'chill'] });
      expect(response.status).toBe(200);
      expect(response.body).toEqual({
        updated: true,
        tags: ['horror', 'chill']
      });

      const { createQueryable } = await import('./client.js');
      const q = createQueryable(pool);
      const rows = await q.query<{
        tag: string;
        added_by_token_id: number | null;
      }>(
        `SELECT tag, added_by_token_id FROM world_tags
         WHERE world_id = 'wrld_horror' ORDER BY added_at, id`
      );
      expect(rows.rows.map((r) => r.tag)).toEqual(['horror', 'chill']);
      expect(rows.rows[0]?.added_by_token_id).not.toBeNull();
    });

    it('rejects invalid tags on the edit endpoint', async () => {
      const response = await request(app)
        .put('/api/worlds/wrld_horror/tags/edit')
        .set('authorization', `Bearer ${curatorToken}`)
        .send({ guildId: 'guild-1', tags: ['nope'] });
      expect(response.status).toBe(400);
    });

    it('requires a valid token', async () => {
      const response = await request(app).get('/api/tags');
      expect(response.status).toBe(401);
    });

    it('GET /api/meta still works', async () => {
      const response = await request(app)
        .get('/api/meta')
        .set('authorization', `Bearer ${viewerToken}`);
      expect(response.status).toBe(200);
      expect(response.body.qualityGood).toBe(1);
      expect(response.body.platformDesktop).toBe(1);
    });
  });
});
